- name: Install Go
  block:
    - name: Fedora | Install Go
      ansible.builtin.dnf:
        name: golang
        state: present
      become: true
      when: ansible_facts["os_family"] == "RedHat"

    - name: macOS | Install Go
      community.general.homebrew:
        name: go
        state: present
      when: ansible_facts["os_family"] == "Darwin"

